// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/kv.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Err mirrors the Go-side rpc.Err type.
type Err int32

const (
	Err_ERR_UNSPECIFIED  Err = 0
	Err_OK               Err = 1
	Err_ERR_NO_KEY       Err = 2
	Err_ERR_VERSION      Err = 3
	Err_ERR_MAYBE        Err = 4 // synthesized by Clerk only; servers never return this
	Err_ERR_WRONG_LEADER Err = 5
	Err_ERR_WRONG_GROUP  Err = 6
)

// Enum value maps for Err.
var (
	Err_name = map[int32]string{
		0: "ERR_UNSPECIFIED",
		1: "OK",
		2: "ERR_NO_KEY",
		3: "ERR_VERSION",
		4: "ERR_MAYBE",
		5: "ERR_WRONG_LEADER",
		6: "ERR_WRONG_GROUP",
	}
	Err_value = map[string]int32{
		"ERR_UNSPECIFIED":  0,
		"OK":               1,
		"ERR_NO_KEY":       2,
		"ERR_VERSION":      3,
		"ERR_MAYBE":        4,
		"ERR_WRONG_LEADER": 5,
		"ERR_WRONG_GROUP":  6,
	}
)

func (x Err) Enum() *Err {
	p := new(Err)
	*p = x
	return p
}

func (x Err) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Err) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kv_proto_enumTypes[0].Descriptor()
}

func (Err) Type() protoreflect.EnumType {
	return &file_proto_kv_proto_enumTypes[0]
}

func (x Err) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Err.Descriptor instead.
func (Err) EnumDescriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{0}
}

// Get RPC — linearizable read.
type GetArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArgs) Reset() {
	*x = GetArgs{}
	mi := &file_proto_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArgs) ProtoMessage() {}

func (x *GetArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArgs.ProtoReflect.Descriptor instead.
func (*GetArgs) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{0}
}

func (x *GetArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Err           Err                    `protobuf:"varint,3,opt,name=err,proto3,enum=proto.Err" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_proto_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{1}
}

func (x *GetReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetReply) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetReply) GetErr() Err {
	if x != nil {
		return x.Err
	}
	return Err_ERR_UNSPECIFIED
}

// Put RPC — CAS write: applies only if server-side version matches.
type PutArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"` // client's expected version; 0 = create-if-missing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutArgs) Reset() {
	*x = PutArgs{}
	mi := &file_proto_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutArgs) ProtoMessage() {}

func (x *PutArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutArgs.ProtoReflect.Descriptor instead.
func (*PutArgs) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{2}
}

func (x *PutArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutArgs) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PutArgs) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type PutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           Err                    `protobuf:"varint,1,opt,name=err,proto3,enum=proto.Err" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutReply) Reset() {
	*x = PutReply{}
	mi := &file_proto_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutReply) ProtoMessage() {}

func (x *PutReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutReply.ProtoReflect.Descriptor instead.
func (*PutReply) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{3}
}

func (x *PutReply) GetErr() Err {
	if x != nil {
		return x.Err
	}
	return Err_ERR_UNSPECIFIED
}

// Append RPC — non-idempotent append (Get→CAS Put loop on server side).
// Resends after uncertainty degrade to at-most-once + ErrMaybe.
type AppendArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // value to append
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendArgs) Reset() {
	*x = AppendArgs{}
	mi := &file_proto_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendArgs) ProtoMessage() {}

func (x *AppendArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendArgs.ProtoReflect.Descriptor instead.
func (*AppendArgs) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{4}
}

func (x *AppendArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AppendArgs) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AppendReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           Err                    `protobuf:"varint,1,opt,name=err,proto3,enum=proto.Err" json:"err,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`      // new value after append
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"` // new version after append
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendReply) Reset() {
	*x = AppendReply{}
	mi := &file_proto_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendReply) ProtoMessage() {}

func (x *AppendReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendReply.ProtoReflect.Descriptor instead.
func (*AppendReply) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{5}
}

func (x *AppendReply) GetErr() Err {
	if x != nil {
		return x.Err
	}
	return Err_ERR_UNSPECIFIED
}

func (x *AppendReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AppendReply) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_proto_kv_proto protoreflect.FileDescriptor

const file_proto_kv_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/kv.proto\x12\x05proto\"\x1b\n" +
	"\aGetArgs\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"X\n" +
	"\bGetReply\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x1c\n" +
	"\x03err\x18\x03 \x01(\x0e2\n" +
	".proto.ErrR\x03err\"K\n" +
	"\aPutArgs\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\"(\n" +
	"\bPutReply\x12\x1c\n" +
	"\x03err\x18\x01 \x01(\x0e2\n" +
	".proto.ErrR\x03err\"4\n" +
	"\n" +
	"AppendArgs\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"[\n" +
	"\vAppendReply\x12\x1c\n" +
	"\x03err\x18\x01 \x01(\x0e2\n" +
	".proto.ErrR\x03err\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion*}\n" +
	"\x03Err\x12\x13\n" +
	"\x0fERR_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\x0e\n" +
	"\n" +
	"ERR_NO_KEY\x10\x02\x12\x0f\n" +
	"\vERR_VERSION\x10\x03\x12\r\n" +
	"\tERR_MAYBE\x10\x04\x12\x14\n" +
	"\x10ERR_WRONG_LEADER\x10\x05\x12\x13\n" +
	"\x0fERR_WRONG_GROUP\x10\x062\x85\x01\n" +
	"\x02KV\x12&\n" +
	"\x03Get\x12\x0e.proto.GetArgs\x1a\x0f.proto.GetReply\x12&\n" +
	"\x03Put\x12\x0e.proto.PutArgs\x1a\x0f.proto.PutReply\x12/\n" +
	"\x06Append\x12\x11.proto.AppendArgs\x1a\x12.proto.AppendReplyB\x0eZ\f6.5840/protob\x06proto3"

var (
	file_proto_kv_proto_rawDescOnce sync.Once
	file_proto_kv_proto_rawDescData []byte
)

func file_proto_kv_proto_rawDescGZIP() []byte {
	file_proto_kv_proto_rawDescOnce.Do(func() {
		file_proto_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kv_proto_rawDesc), len(file_proto_kv_proto_rawDesc)))
	})
	return file_proto_kv_proto_rawDescData
}

var file_proto_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_kv_proto_goTypes = []any{
	(Err)(0),            // 0: proto.Err
	(*GetArgs)(nil),     // 1: proto.GetArgs
	(*GetReply)(nil),    // 2: proto.GetReply
	(*PutArgs)(nil),     // 3: proto.PutArgs
	(*PutReply)(nil),    // 4: proto.PutReply
	(*AppendArgs)(nil),  // 5: proto.AppendArgs
	(*AppendReply)(nil), // 6: proto.AppendReply
}
var file_proto_kv_proto_depIdxs = []int32{
	0, // 0: proto.GetReply.err:type_name -> proto.Err
	0, // 1: proto.PutReply.err:type_name -> proto.Err
	0, // 2: proto.AppendReply.err:type_name -> proto.Err
	1, // 3: proto.KV.Get:input_type -> proto.GetArgs
	3, // 4: proto.KV.Put:input_type -> proto.PutArgs
	5, // 5: proto.KV.Append:input_type -> proto.AppendArgs
	2, // 6: proto.KV.Get:output_type -> proto.GetReply
	4, // 7: proto.KV.Put:output_type -> proto.PutReply
	6, // 8: proto.KV.Append:output_type -> proto.AppendReply
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_kv_proto_init() }
func file_proto_kv_proto_init() {
	if File_proto_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kv_proto_rawDesc), len(file_proto_kv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kv_proto_goTypes,
		DependencyIndexes: file_proto_kv_proto_depIdxs,
		EnumInfos:         file_proto_kv_proto_enumTypes,
		MessageInfos:      file_proto_kv_proto_msgTypes,
	}.Build()
	File_proto_kv_proto = out.File
	file_proto_kv_proto_goTypes = nil
	file_proto_kv_proto_depIdxs = nil
}
